language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install codecov

script:
  - pytest . -v --cov=.

after_success:
  - codecov

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    python: "3.5"
    tags: true
    repo: aliciawyy/pymerkletools
